trigger:
- master
pool:
  vmImage: 'vs2017-win2016'
steps:
  - task: DotNetCoreInstaller@0
    inputs:
       version: '2.2.100' # replace this value with the version that you need for your project
  - script: |
       dotnet tool install -g Cake.Tool
       dotnet cake build.cake
       tree
       cd output
       tree
